[agent]
  interval = "300s"
  flush_interval = "300s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-secret-token-123"
  organization = "my-org"
  bucket = "system_metrics"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]